// This file is automatically generated by Diesel CLI
diesel::table! {
    articles (id) {
        id -> Int4,
        title -> Varchar,
        description -> Text,
    }
}

diesel::table! {
    books (isbn) {
        isbn -> Varchar,
        title -> Varchar,
        author -> Varchar,
        publication_year -> Varchar,
        publisher -> Varchar,
        image_url -> Varchar,
    }
}